/**
 * FormDefinition v2 schemas extracted from React order components.
 * Used for seeding ServiceRequirementSchema and admin CMS defaults.
 */

export const DEFAULT_NEW_SERVICE_FORM = {
  version: 2 as const,
  stepLabels: ['تفاصيل المشروع', 'الملفات والمتطلبات'],
  sections: [
    {
      id: 'project',
      step: '01',
      icon: '📋',
      title: 'تفاصيل ومتطلبات الخدمة',
      desc: 'يرجى تزويدنا بكافة المعلومات المتعلقة بطلبك لسرعة البدء في التنفيذ',
      fields: [
        {
          id: 'projectTitle',
          type: 'text' as const,
          label: 'اسم المشروع / العلامة التجارية',
          outputKey: 'اسم المشروع',
          icon: '🏷️',
          required: true,
          placeholder: 'اكتب اسم المنشأة أو المشروع...',
        },
        {
          id: 'projectDetails',
          type: 'textarea' as const,
          label: 'شرح وتفاصيل المتطلبات',
          outputKey: 'تفاصيل الطلب',
          icon: '📝',
          required: true,
          rows: 4,
          placeholder: 'اشرح بالتفصيل ما ترغب في إنجازه، الأهداف، وأي ملاحظات خاصة...',
        },
        {
          id: 'preferredTimeline',
          type: 'select' as const,
          label: 'الوقت المفضل للتسليم',
          outputKey: 'الوقت المفضل للتسليم',
          icon: '⏱️',
          required: false,
          defaultValue: 'عاجل (خلال أيام قليلة)',
          options: [
            {
              value: 'عاجل (خلال أيام قليلة)',
              label: 'عاجل (أولوية تنفيذ خلال أيام قليلة)',
            },
            {
              value: 'عادي (حسب جدول التسليم القياسي)',
              label: 'عادي (حسب جدول التسليم القياسي للخدمة)',
            },
            {
              value: 'مرن (لدينا متسع من الوقت)',
              label: 'مرن (لا يوجد موعد محدد)',
            },
          ],
        },
        {
          id: 'attachedFiles',
          type: 'file' as const,
          label: 'الملفات والمستندات المرفقة',
          outputKey: 'الملفات المرفقة',
          icon: '📁',
          multiple: true,
        },
      ],
    },
  ],
};

export function getDefaultFormForNewService() {
  return DEFAULT_NEW_SERVICE_FORM;
}

const SOCIAL_MEDIA_POSTS_FORM = {
  version: 2 as const,
  stepLabels: ['المنصات والخدمة', 'النشاط والجمهور', 'العروض والنبرة', 'الملفات والمرفقات'],
  guaranteesTitle: 'ضمانات كوبالت لخدمات منشورات السوشيال ميديا',
  guarantees: [
    {
      icon: '📁',
      title: 'ملكية كاملة لكافة الملفات والمصادر',
      desc: 'تسليم ملفات التصاميم المصدرية المفتوحة وقوالب العمل بجودة عالية فور الاعتماد.',
    },
    {
      icon: '⏱️',
      title: 'التزام تام بالخطة الزمنية',
      desc: 'تسليم البوستات والستوريز والمحتوى الإعلاني في الموعد المحدد دون أي تأخير.',
    },
    {
      icon: '🔄',
      title: 'تعديلات مستمرة حتى الرضا',
      desc: 'تعديلات ومراجعات مجانية متواصلة حتى الوصول للشكل والنسق الجذاب المناسب لهوية حسابك.',
    },
  ],
  sections: [
    {
      id: 'platforms-service',
      step: '01',
      icon: '🌐',
      title: 'المنصات المطلوبة ونوع الخدمة',
      desc: 'حدد قنوات التواصل المستهدفة وطبيعة الخدمة المطلوبة لحساباتك',
      fields: [
        {
          id: 'platforms',
          type: 'multichip' as const,
          label: 'المنصات المطلوبة للنشر والتصميم',
          outputKey: 'المنصات المطلوبة',
          icon: '📱',
          required: true,
          defaultValue: ['انستقرام Instagram'],
          options: [
            { value: 'انستقرام Instagram', label: 'انستقرام (Instagram)' },
            { value: 'سناب شات Snapchat', label: 'سناب شات (Snapchat)' },
            { value: 'تيك توك TikTok', label: 'تيك توك (TikTok)' },
            { value: 'إكس / تويتر X', label: 'إكس (Twitter / X)' },
            { value: 'لينكد إن LinkedIn', label: 'لينكد إن (LinkedIn)' },
            { value: 'فيسبوك Facebook', label: 'فيسبوك (Facebook)' },
            { value: 'يوتيوب YouTube', label: 'يوتيوب (YouTube)' },
            { value: 'بينترست Pinterest', label: 'بينترست (Pinterest)' },
          ],
        },
        {
          id: 'currentAccounts',
          type: 'url_list' as const,
          label: 'روابط الحسابات الحالية على وسائل التواصل',
          outputKey: 'روابط الحسابات الحالية',
          placeholder: 'https://instagram.com/youraccount',
          addButtonLabel: '➕ إضافة رابط حساب آخر',
        },
        {
          id: 'serviceType',
          type: 'select' as const,
          label: 'نوع الخدمة المطلوبة',
          outputKey: 'نوع الخدمة',
          icon: '🛠️',
          required: true,
          defaultValue: 'محتوى + تصميم',
          options: [
            {
              value: 'محتوى + تصميم',
              label: 'محتوى بيعي + تصاميم جرافيك مميزة (Content Writing + Design)',
            },
            { value: 'تصميم فقط', label: 'تصميم جرافيك فقط (Graphic Design Only)' },
            {
              value: 'إدارة كاملة',
              label: 'إدارة ونشر متكاملة (Full Management + Posting + Interaction)',
            },
          ],
        },
      ],
    },
    {
      id: 'activity-audience',
      step: '02',
      icon: '🎯',
      title: 'تفاصيل النشاط والجمهور المستهدف',
      desc: 'توضيح مجال العمل وخصائص العملاء المستهدفين لبناء استراتيجية محتوى جذابة',
      fields: [
        {
          id: 'activityField',
          type: 'text' as const,
          label: 'مجال النشاط والقطاع التجاري',
          outputKey: 'مجال النشاط',
          icon: '🏢',
          required: true,
          placeholder: 'مثال: متجر عطور فاخرة، شركة عقارية، عيادة أسنان، تطبيق توصيل...',
        },
        {
          id: 'targetAudience',
          type: 'textarea' as const,
          label: 'الجمهور والعملاء المستهدفين',
          outputKey: 'الجمهور المستهدف',
          icon: '👥',
          required: true,
          rows: 3,
          placeholder:
            'حدد فئة عملائك: الفئات العمرية، الاهتمامات، النطاق الجغرافي (رجال/نساء، مهتمين بالتقنية أو الموضة)...',
        },
        {
          id: 'mainGoals',
          type: 'multichip' as const,
          label: 'الهدف الرئيسي من التواجد الرقمي',
          outputKey: 'الهدف الرئيسي',
          icon: '🚀',
          required: true,
          defaultValue: ['مبيعات Direct Sales', 'انتشار Brand Awareness'],
          options: [
            { value: 'مبيعات Direct Sales', label: 'مبيعات مباشرة (Sales)' },
            { value: 'انتشار Brand Awareness', label: 'انتشار وشهرة (Awareness)' },
            { value: 'تفاعل Engagement', label: 'تفاعل ومتابعين (Engagement)' },
            { value: 'جمع بيانات عملاء Leads', label: 'عملاء محتملين (Leads)' },
            { value: 'زيارات للموقع / المتجر Traffic', label: 'زيارات للموقع (Traffic)' },
          ],
        },
        {
          id: 'keyProducts',
          type: 'textarea' as const,
          label: 'أهم الخدمات / المنتجات المراد التركيز عليها',
          outputKey: 'أهم الخدمات والمنتجات',
          icon: '✨',
          required: true,
          rows: 3,
          placeholder: 'أذكر أبرز 3-5 خدمات أو منتجات تريد التركيز على إبراز مميزاتها في المنشورات...',
        },
      ],
    },
    {
      id: 'offers-tone',
      step: '03',
      icon: '🗣️',
      title: 'العروض ونبرة التخاطب واللغة',
      desc: 'ضبط اللهجة ونبرة الخطاب التي تناسب علامتك وتصل للجمهور بفاعلية',
      fields: [
        {
          id: 'hasOffers',
          type: 'yesno' as const,
          label: 'هل توجد عروض حالية أو خصومات ترويجية؟',
          outputKey: 'هل توجد عروض؟',
          icon: '🏷️',
          required: true,
          defaultValue: 'no' as const,
          yesLabel: 'نعم (لدينا عروض وخصومات)',
          noLabel: 'لا (محتوى تعريفي عام)',
        },
        {
          id: 'offersDetails',
          type: 'textarea' as const,
          label: 'تفاصيل العروض والخصومات',
          icon: '📝',
          required: true,
          rows: 2,
          placeholder: 'اكتب تفاصيل الخصم، كود العرض، مدة العرض أو الباقات الترويجية...',
          showIf: { field: 'hasOffers', equals: 'yes' },
        },
        {
          id: 'language',
          type: 'select' as const,
          label: 'لغة المحتوى والتصاميم',
          outputKey: 'اللغة',
          icon: '🌐',
          required: true,
          defaultValue: 'العربية (Arabic)',
          options: [
            { value: 'العربية (Arabic)', label: 'العربية (Arabic)' },
            { value: 'الإنجليزية (English)', label: 'الإنجليزية (English)' },
            { value: 'ثنائي اللغة (عربي + إنجليزي)', label: 'كلاهما (عربي + إنجليزي)' },
            { value: 'لغة أخرى', label: 'لغة أخرى' },
          ],
        },
        {
          id: 'toneOfVoice',
          type: 'select' as const,
          label: 'نبرة التخاطب (Tone of Voice)',
          outputKey: 'Tone of Voice',
          icon: '🎙️',
          required: false,
          defaultValue: 'عصري وشبابي',
          options: [
            { value: 'عصري وشبابي', label: 'عصري وشبابي وتفاعلي (Modern & Engaging)' },
            { value: 'رسمي ومؤسسي', label: 'رسمي ومؤسسي وقوي (Corporate & Professional)' },
            { value: 'ودود وقريب للعميل', label: 'ودود وقريب وبسيط (Friendly & Warm)' },
            { value: 'تسويقي ومحفز', label: 'تسويقي ومحفز للشراء (Persuasive & Sales-driven)' },
            { value: 'فاخر وراقي', label: 'فاخر وراقي (Luxury & High-end)' },
          ],
        },
      ],
    },
    {
      id: 'files-refs',
      step: '04',
      icon: '📁',
      title: 'الملفات والمرفقات والحسابات المرجعية',
      desc: 'إرفاق الشعار، صور المنتجات، ودليل الهوية لضمان تناسق وجودة التصاميم',
      fields: [
        {
          id: 'logoFiles',
          type: 'file' as const,
          label: 'الشعار (Logo) بدقة عالية',
          outputKey: 'الشعار المرفوع',
          accept: 'image/*,.ai,.eps,.pdf,.svg',
          required: true,
        },
        {
          id: 'brandFiles',
          type: 'file' as const,
          label: 'دليل الهوية البصرية (Brand Guidelines)',
          outputKey: 'ملفات الهوية والمرفقات',
          icon: '🎨',
          accept: '.pdf,.ai,.zip,.png,.jpg',
        },
        {
          id: 'productFiles',
          type: 'file' as const,
          label: 'صور المنتجات والمواد الخام',
          outputKey: 'ملفات الهوية والمرفقات',
          icon: '📸',
          accept: 'image/*,.zip',
          multiple: true,
        },
        {
          id: 'videoFiles',
          type: 'file' as const,
          label: 'مقاطع الفيديو والمونتاج إن وجدت',
          outputKey: 'ملفات الهوية والمرفقات',
          icon: '🎥',
          accept: 'video/*,.zip',
          multiple: true,
        },
        {
          id: 'priceFiles',
          type: 'file' as const,
          label: 'قائمة الأسعار والمنيو (Price List / Menu)',
          outputKey: 'ملفات الهوية والمرفقات',
          icon: '💰',
          accept: '.pdf,.xls,.xlsx,.csv,image/*',
        },
        {
          id: 'refAccounts',
          type: 'url_list' as const,
          label: 'حسابات أو تصاميم مرجعية تفضل أسلوبها',
          outputKey: 'الحسابات المرجعية',
          placeholder: 'https://instagram.com/inspirational_account',
          addButtonLabel: '➕ إضافة رابط حساب مرجعي آخر',
        },
      ],
    },
  ],
};

const WEBSITE_DESIGN_FORM = {
  version: 2 as const,
  stepLabels: ['هوية ونوع الموقع', 'الصفحات والمحتوى', 'الوظائف والاستضافة'],
  guaranteesTitle: 'ضمانات كوبالت لخدمات تصميم وتطوير المواقع',
  guarantees: [
    {
      icon: '📁',
      title: 'ملكية السورس كود والتصميم 100%',
      desc: 'تسليم كافة الملفات المصدرية للأكواد والتصميم (Figma, React/Next.js Source Code) فور الاعتماد.',
    },
    {
      icon: '⏱️',
      title: 'سرعة وأداء فائق متوافق مع SEO',
      desc: 'نضمن سرعة تحميل خارقة على Google PageSpeed وتصفح متجاوب بالكامل مع كافة الشاشات والموبايل.',
    },
    {
      icon: '🔄',
      title: 'دعم فني وصيانة مجانية',
      desc: 'دعم فني وضمان استقرار ونسخ احتياطي ومتابعة لمدة شهر كامل بعد إطلاق الموقع مجاناً.',
    },
  ],
  sections: [
    {
      id: 'identity',
      step: '01',
      icon: '🏢',
      title: 'نوع الموقع وهوية المشروع',
      desc: 'حدد نوع الموقع وطبيعة نشاط الشركة لتهيئة التصميم والهيكل العام للمشروع',
      fields: [
        {
          id: 'siteType',
          type: 'select' as const,
          label: 'نوع الموقع المطلوب',
          outputKey: 'نوع الموقع',
          icon: '🌐',
          required: true,
          defaultValue: 'شركة (Corporate Website)',
          options: [
            { value: 'شركة (Corporate Website)', label: 'موقع شركة ومؤسسة (Corporate Website)' },
            { value: 'صفحة هبوط (Landing Page)', label: 'صفحة هبوط تسويقية (Landing Page)' },
            { value: 'معرض أعمال (Portfolio)', label: 'معرض أعمال وسيرة مهنية (Portfolio)' },
            { value: 'موقع خدمات (Services Site)', label: 'موقع عرض وحجز خدمات (Services Site)' },
            { value: 'موقع حجوزات ومواعيد (Booking)', label: 'موقع حجوزات ومواعيد واستشارات (Booking)' },
            { value: 'أخرى (Other)', label: 'نوع آخر مخصص (Other)' },
          ],
        },
        {
          id: 'projectName',
          type: 'text' as const,
          label: 'اسم المشروع / الشركة',
          outputKey: 'اسم المشروع',
          icon: '🏷️',
          required: true,
          placeholder: 'اكتب الاسم التجاري أو اسم المنشأة...',
        },
        {
          id: 'activityDesc',
          type: 'textarea' as const,
          label: 'وصف النشاط والخدمات',
          outputKey: 'وصف النشاط',
          icon: '📝',
          required: true,
          rows: 3,
          placeholder: 'نبذة تعريفية عن الشركة، ما تقدمه من خدمات، ورسالتها الأساسية للزوار...',
        },
        {
          id: 'logoFiles',
          type: 'file' as const,
          label: 'الشعار الرسمي (Logo)',
          outputKey: 'الشعار والمرفقات',
          accept: 'image/*,.ai,.svg,.pdf',
          icon: '🖼️',
          required: true,
        },
        {
          id: 'brandFiles',
          type: 'file' as const,
          label: 'دليل الهوية والألوان (Brand Guidelines)',
          outputKey: 'الشعار والمرفقات',
          icon: '🎨',
          accept: '.pdf,.ai,.zip,.png,.jpg',
        },
        {
          id: 'hasCurrentSite',
          type: 'yesno' as const,
          label: 'هل يوجد موقع إلكتروني حالي للشركة؟',
          outputKey: 'هل يوجد موقع حالي؟',
          icon: '🌐',
          required: true,
          defaultValue: 'no' as const,
          yesLabel: 'نعم (إعادة تصميم وتطوير)',
          noLabel: 'لا (موقع جديد كلياً)',
        },
        {
          id: 'currentSiteUrl',
          type: 'text' as const,
          label: 'رابط الموقع الحالي',
          icon: '🔗',
          required: true,
          placeholder: 'https://your-current-website.com',
          showIf: { field: 'hasCurrentSite', equals: 'yes' },
        },
      ],
    },
    {
      id: 'pages-content',
      step: '02',
      icon: '📑',
      title: 'الصفحات والمحتوى والوسائط',
      desc: 'حدد قائمة الصفحات المطلوبة وجاهزية المحتوى النصي والصور المرفقة',
      fields: [
        {
          id: 'pages',
          type: 'multichip' as const,
          label: 'الصفحات المطلوبة في الموقع',
          outputKey: 'الصفحات المطلوبة',
          icon: '📄',
          required: true,
          defaultValue: [
            'الرئيسية (Home)',
            'من نحن (About Us)',
            'الخدمات (Services)',
            'اتصل بنا (Contact Us)',
          ],
          options: [
            { value: 'الرئيسية (Home)', label: 'الرئيسية (Home)' },
            { value: 'من نحن (About Us)', label: 'من نحن (About Us)' },
            { value: 'الخدمات (Services)', label: 'الخدمات (Services)' },
            {
              value: 'سابقة الأعمال / المعرض (Portfolio)',
              label: 'سابقة الأعمال (Portfolio)',
            },
            { value: 'المدونة والمقالات (Blog)', label: 'المدونة (Blog)' },
            { value: 'اتصل بنا (Contact Us)', label: 'اتصل بنا (Contact Us)' },
            { value: 'الأسئلة الشائعة (FAQ)', label: 'الأسئلة الشائعة (FAQ)' },
            { value: 'فريق العمل (Our Team)', label: 'فريق العمل (Our Team)' },
            { value: 'حجز موعد / استشارة (Booking)', label: 'حجز موعد (Booking)' },
            { value: 'صفحة أخرى مخصصة', label: 'أخرى مخصصة' },
          ],
        },
        {
          id: 'contentReady',
          type: 'select' as const,
          label: 'هل المحتوى النصي للموقع جاهز؟',
          outputKey: 'حالة المحتوى',
          icon: '✍️',
          required: true,
          defaultValue: 'جزئي',
          options: [
            { value: 'نعم', label: 'نعم، جاهز بالكامل (Yes, fully ready)' },
            { value: 'جزئي', label: 'جزئي (يحتاج صياغة وتنسيق)' },
            { value: 'لا', label: 'لا (نحتاج كتابة المحتوى وصياغته من قبلكم)' },
          ],
        },
        {
          id: 'contentFiles',
          type: 'file' as const,
          label: 'رفع ملفات المحتوى النصي',
          outputKey: 'الشعار والمرفقات',
          icon: '📄',
          accept: '.doc,.docx,.pdf,.txt',
          multiple: true,
          showIf: { field: 'contentReady', equals: ['نعم', 'جزئي'] },
        },
        {
          id: 'photoFiles',
          type: 'file' as const,
          label: 'صور المنشأة والمشاريع',
          outputKey: 'الشعار والمرفقات',
          icon: '📸',
          accept: 'image/*,.zip',
          multiple: true,
        },
        {
          id: 'videoFiles',
          type: 'file' as const,
          label: 'مقاطع الفيديو للموقع إن وجدت',
          outputKey: 'الشعار والمرفقات',
          icon: '🎥',
          accept: 'video/*,.zip',
          multiple: true,
        },
        {
          id: 'language',
          type: 'select' as const,
          label: 'لغات الموقع المطلوب',
          outputKey: 'اللغة',
          icon: '🌐',
          required: true,
          defaultValue: 'العربية (Arabic)',
          options: [
            { value: 'العربية (Arabic)', label: 'العربية فقط (Arabic)' },
            { value: 'الإنجليزية (English)', label: 'الإنجليزية فقط (English)' },
            {
              value: 'ثنائي اللغة (عربي + إنجليزي)',
              label: 'ثنائي اللغة (عربي + إنجليزي متكامل)',
            },
            { value: 'لغات أخرى', label: 'لغات أخرى مخصصة' },
          ],
        },
        {
          id: 'refUrls',
          type: 'url_list' as const,
          label: 'مواقع مرجعية تفضل أسلوب تصميمها',
          outputKey: 'المواقع المرجعية',
          placeholder: 'https://example.com',
          addButtonLabel: '➕ إضافة موقع مرجعي آخر',
        },
      ],
    },
    {
      id: 'features-hosting',
      step: '03',
      icon: '⚙️',
      title: 'الوظائف المطلوبة والنطاق والاستضافة',
      desc: 'تحديد الميزات التفاعلية وحالة النطاق (Domain) والاستضافة السحابية',
      fields: [
        {
          id: 'features',
          type: 'multichip' as const,
          label: 'الوظائف والخصائص البرمجية المطلوبة',
          outputKey: 'الوظائف المطلوبة',
          icon: '⚙️',
          required: true,
          defaultValue: [
            'زر واتساب مباشر (WhatsApp)',
            'استمارة تواصل (Contact / Form)',
            'خرائط جوجل (Google Maps)',
          ],
          options: [
            { value: 'استمارة تواصل (Contact / Form)', label: 'نموذج تواصل (Contact Form)' },
            { value: 'زر واتساب مباشر (WhatsApp)', label: 'واتساب مباشر (WhatsApp)' },
            { value: 'بوابة دفع إلكتروني (Payment)', label: 'بوابة دفع (Payment)' },
            { value: 'نظام حجز ومواعيد (Booking)', label: 'نظام حجوزات (Booking)' },
            { value: 'خرائط جوجل (Google Maps)', label: 'خرائط جوجل (Maps)' },
            { value: 'مدونة مقالات (Blog)', label: 'مدونة مقالات (Blog)' },
            { value: 'شات ومحادثة حية (Live Chat)', label: 'محادثة حية (Live Chat)' },
            { value: 'نشرة بريدية (Newsletter)', label: 'نشرة بريدية (Newsletter)' },
            {
              value: 'حسابات وتسجيل أعضاء (User Accounts)',
              label: 'حسابات مستخدمين (Accounts)',
            },
            { value: 'تعدد اللغات (Multilingual)', label: 'تعدد لغات (Multilingual)' },
            { value: 'خصائص برمجية أخرى (Other)', label: 'وظائف أخرى مخصصة' },
          ],
        },
        {
          id: 'hasDomain',
          type: 'yesno' as const,
          label: 'هل لديك اسم نطاق (Domain) محجوز؟',
          outputKey: 'الدومين',
          icon: '🌐',
          required: true,
          defaultValue: 'no' as const,
          yesLabel: 'نعم (لدي دومين جاهز)',
          noLabel: 'لا (نحتاج حجز دومين جديد)',
        },
        {
          id: 'domainName',
          type: 'text' as const,
          label: 'اكتب اسم الدومين المحجوز',
          icon: '🔗',
          required: true,
          placeholder: 'example.com أو company.sa',
          showIf: { field: 'hasDomain', equals: 'yes' },
        },
        {
          id: 'hasHosting',
          type: 'yesno' as const,
          label: 'هل لديك استضافة وسيرفر (Hosting)؟',
          outputKey: 'الاستضافة',
          icon: '☁️',
          required: true,
          defaultValue: 'no' as const,
          yesLabel: 'نعم (لدي استضافة خاصة)',
          noLabel: 'لا (وفروا استضافة سريعة مع الباقة)',
        },
        {
          id: 'hostingProvider',
          type: 'text' as const,
          label: 'اسم مزود الاستضافة أو بيانات السيرفر',
          icon: '🏢',
          required: true,
          placeholder: 'مثال: Hostinger, Siteground, AWS, Cloudways, cPanel...',
          showIf: { field: 'hasHosting', equals: 'yes' },
        },
      ],
    },
  ],
};

const ECOMMERCE_STORE_FORM = {
  version: 2 as const,
  stepLabels: ['المنتجات والمخزون', 'بوابات الدفع والشحن', 'سياسات المتجر'],
  guaranteesTitle: 'ضمانات كوبالت لخدمات المتاجر الإلكترونية',
  guarantees: [
    {
      icon: '💳',
      title: 'ربط بوابات الدفع والتحقق 100%',
      desc: 'نضمن اختبار عمليات الشراء الحية وربط مدى وApple Pay وتابي وتمارا والفيزا بنجاح تام.',
    },
    {
      icon: '⏱️',
      title: 'جاهزية فورية للمبيعات',
      desc: 'تسليم متجر جاهز تقنياً وبصرياً لإطلاق الحملات الإعلانية واستقبال طلبات العملاء مباشرة.',
    },
    {
      icon: '🔄',
      title: 'دعم فني وتدريب على الإدارة',
      desc: 'تدريب كامل ومفصل لك ولفريقك على كيفية إضافة المنتجات وإدارة الفواتير والطلبات والمخزون.',
    },
  ],
  sections: [
    {
      id: 'products',
      step: '01',
      icon: '📦',
      title: 'المنتجات، التصنيفات وملفات الأسعار',
      desc: 'حدد تفاصيل منتجاتك وأقسام المتجر لتجهيز قاعدة البيانات ورفع المنتجات باحترافية',
      fields: [
        {
          id: 'productsCount',
          type: 'text' as const,
          label: 'عدد المنتجات التقريبي المراد إدراجها',
          outputKey: 'عدد المنتجات',
          icon: '🔢',
          required: true,
          placeholder: 'مثال: 50 منتج',
          defaultValue: '30',
        },
        {
          id: 'categoriesText',
          type: 'textarea' as const,
          label: 'تصنيفات وأقسام المنتجات (Categories)',
          outputKey: 'تصنيفات المنتجات',
          icon: '📂',
          required: true,
          rows: 3,
          placeholder:
            'أدخل أسماء الأقسام الرئيسية والفرعية (مثال: عطور رجالية، عطور نسائية، بخور، هدايا)...',
        },
        {
          id: 'csvFiles',
          type: 'file' as const,
          label: 'ملف المنتجات والتفاصيل (CSV / Excel)',
          outputKey: 'ملف المنتجات',
          icon: '📊',
          accept: '.csv,.xlsx,.xls',
          required: true,
        },
        {
          id: 'photoFiles',
          type: 'file' as const,
          label: 'صور المنتجات عالية الدقة',
          outputKey: 'صور المنتجات',
          icon: '📸',
          accept: 'image/*,.zip',
          multiple: true,
          required: true,
        },
        {
          id: 'priceFiles',
          type: 'file' as const,
          label: 'قائمة الأسعار والعروض الترويجية',
          outputKey: 'ملف الأسعار',
          icon: '💰',
          accept: '.csv,.xlsx,.xls,.pdf,image/*',
          required: true,
        },
        {
          id: 'inventoryType',
          type: 'select' as const,
          label: 'منصة المتجر وإدارة المخزون (Stock & Platform)',
          outputKey: 'المخزون والمنصة',
          icon: '🏢',
          required: false,
          defaultValue: 'متجر سلة (Salla)',
          options: [
            { value: 'متجر سلة (Salla)', label: 'منصة سلة (Salla Platform)' },
            { value: 'منصة زد (Zid)', label: 'منصة زد (Zid Platform)' },
            { value: 'شوبيفاي (Shopify)', label: 'منصة شوبيفاي (Shopify)' },
            { value: 'ووكومرس (WooCommerce)', label: 'ووكومرس مخصص (WooCommerce)' },
            { value: 'ربط عبر نظام ERP / API', label: 'ربط نظام محاسبي ERP / API' },
            { value: 'ملف إكسيل منفصل', label: 'ملف مخزون يدوي' },
          ],
        },
        {
          id: 'inventoryFiles',
          type: 'file' as const,
          label: 'ملف المخزون',
          icon: '📑',
          accept: '.csv,.xlsx,.xls',
        },
      ],
    },
    {
      id: 'payment-shipping',
      step: '02',
      icon: '💳',
      title: 'بوابات الدفع، الشحن والضرائب',
      desc: 'حدد قنوات الدفع المفضلة ومناطق الشحن لتهيئة تجربة شراء متكاملة لعملائك',
      fields: [
        {
          id: 'paymentMethods',
          type: 'multichip' as const,
          label: 'طرق وبوابات الدفع المطلوبة للربط',
          outputKey: 'طرق الدفع المطلوبة',
          icon: '💳',
          required: true,
          defaultValue: [
            'مدى (Mada)',
            'Apple Pay',
            'فيزا وماستركارد (Visa/MasterCard)',
            'تمارا (Tamara)',
            'تابي (Tabby)',
          ],
          options: [
            { value: 'مدى (Mada)', label: 'مدى (Mada)' },
            { value: 'Apple Pay', label: 'Apple Pay' },
            { value: 'فيزا وماستركارد (Visa/MasterCard)', label: 'Visa / MasterCard' },
            { value: 'تمارا (Tamara)', label: 'تمارا (Tamara)' },
            { value: 'تابي (Tabby)', label: 'تابي (Tabby)' },
            { value: 'الدفع عند الاستلام (COD)', label: 'الدفع عند الاستلام (COD)' },
            { value: 'STC Pay', label: 'STC Pay' },
            { value: 'تحويل بنكي مباشر', label: 'تحويل بنكي' },
            { value: 'باي بال (PayPal)', label: 'PayPal' },
          ],
        },
        {
          id: 'targetCountries',
          type: 'multichip' as const,
          label: 'الدول المستهدفة للبيع والشحن',
          outputKey: 'الدول المستهدفة',
          icon: '🌍',
          required: true,
          defaultValue: [
            'المملكة العربية السعودية',
            'الإمارات العربية المتحدة',
            'الكويت',
          ],
          options: [
            { value: 'المملكة العربية السعودية', label: '🇸🇦 السعودية' },
            { value: 'الإمارات العربية المتحدة', label: '🇦🇪 الإمارات' },
            { value: 'الكويت', label: '🇰🇼 الكويت' },
            { value: 'قطر', label: '🇶🇦 قطر' },
            { value: 'البحرين', label: '🇧🇭 البحرين' },
            { value: 'سلطنة عمان', label: '🇴🇲 عمان' },
            { value: 'مصر', label: '🇪🇬 مصر' },
            { value: 'كافة دول الخليج العربي', label: 'دول الخليج كافة' },
            { value: 'شحن دولي لكافة أنحاء العالم', label: 'جميع دول العالم' },
          ],
        },
        {
          id: 'shippingZones',
          type: 'textarea' as const,
          label: 'مناطق وتغطية الشحن والتوصيل',
          outputKey: 'مناطق الشحن',
          icon: '🚚',
          required: true,
          rows: 2,
          placeholder:
            'أدخل المدن والمناطق المغطاة (مثال: جميع مدن المملكة والقرى، توصيل سريع بالرياض، وشحن دولي للخليج)...',
        },
        {
          id: 'shippingCompanies',
          type: 'text' as const,
          label: 'شركات الشحن المفضلة للربط',
          outputKey: 'شركات الشحن',
          icon: '🏢',
          required: false,
          placeholder: 'مثال: أرامكس (Aramex)، سمسا (SMSA)، DHL، سبل، مندوب خاص...',
        },
        {
          id: 'hasVat',
          type: 'yesno' as const,
          label: 'هل المتجر خاضع لضريبة القيمة المضافة (VAT)؟',
          outputKey: 'الضريبة',
          icon: '🏛️',
          required: true,
          defaultValue: 'yes' as const,
          yesLabel: 'نعم (15% ضريبة مضافة)',
          noLabel: 'لا (غير مسجل ضريبياً)',
        },
        {
          id: 'storeCurrency',
          type: 'select' as const,
          label: 'العملة الأساسية للمتجر',
          outputKey: 'العملة الأساسية',
          icon: '💱',
          required: true,
          defaultValue: 'SAR (ريال سعودي)',
          options: [
            { value: 'SAR (ريال سعودي)', label: '🇸🇦 ريال سعودي (SAR)' },
            { value: 'AED (درهم إماراتي)', label: '🇦🇪 درهم إماراتي (AED)' },
            { value: 'USD (دولار أمريكي)', label: '🇺🇸 دولار أمريكي (USD)' },
            { value: 'KWD (دينار كويتي)', label: '🇰🇼 دينار كويتي (KWD)' },
            { value: 'QAR (ريال قطري)', label: '🇶🇦 ريال قطري (QAR)' },
            { value: 'BHD (دينار بحريني)', label: '🇧🇭 دينار بحريني (BHD)' },
            { value: 'OMR (ريال عماني)', label: '🇴🇲 ريال عماني (OMR)' },
            { value: 'EGP (جنيه مصري)', label: '🇪🇬 جنيه مصري (EGP)' },
          ],
        },
      ],
    },
    {
      id: 'policies',
      step: '03',
      icon: '📜',
      title: 'سياسات المتجر (الشحن، الاسترجاع والخصوصية)',
      desc: 'صياغة شروط المتجر القانونية والتشغيلية المعتمدة لحماية المتجر وبناء ثقة العملاء',
      fields: [
        {
          id: 'shippingPolicy',
          type: 'textarea' as const,
          label: 'سياسة الشحن والتوصيل (Shipping Policy)',
          outputKey: 'سياسة الشحن',
          icon: '📦',
          required: false,
          rows: 2,
          placeholder:
            'اكتب شروط وأوقات الشحن والتوصيل، أو اتركها لنقوم بصياغتها باحترافية حسب الأنظمة الرسمية...',
        },
        {
          id: 'returnPolicy',
          type: 'textarea' as const,
          label: 'سياسة الاسترجاع والاستبدال (Refund & Return Policy)',
          outputKey: 'سياسة الاسترجاع',
          icon: '🔄',
          required: false,
          rows: 2,
          placeholder:
            'اكتب مدة وشروط الاسترجاع والاستبدال المعتمدة لديك، أو اتركها لنقوم بصياغتها...',
        },
        {
          id: 'privacyPolicy',
          type: 'textarea' as const,
          label: 'سياسة الخصوصية وحماية بيانات العملاء (Privacy Policy)',
          outputKey: 'سياسة الخصوصية',
          icon: '🔒',
          required: false,
          rows: 2,
          placeholder:
            'اكتب شروط الخصوصية أو سنقوم بتهيئة السياسة المعتمدة لوزارة التجارة وهيئة البيانات...',
        },
      ],
    },
  ],
};

const MOTION_GRAPHICS_FORM = {
  version: 2 as const,
  stepLabels: ['الأهداف والمنصات', 'السيناريو والرسالة', 'التعليق الصوتي والمرفقات'],
  guaranteesTitle: 'ضمانات كوبالت لخدمات الموشن جرافيك وإنتاج الفيديو',
  guarantees: [
    {
      icon: '🎬',
      title: 'ملكية الفيديو والمصادر 100%',
      desc: 'تسليم الفيديو بدقة 4K / Full HD مع كامل ملفات المشروع الصوتية والبصرية وقوالب العمل المفتوحة.',
    },
    {
      icon: '🎙️',
      title: 'تعليق صوتي استوديو نقي',
      desc: 'تسجيل عبر نخبة من أفضل المعلقين الصوتيين في الوطن العربي بأعلى نقاوة صوتية مع المؤثرات الاحترافية.',
    },
    {
      icon: '🔄',
      title: 'تعديلات غير محدودة للمشاهد',
      desc: 'تعديلات ومراجعات مجانية حتى الوصول لأعلى درجات الإبهار والجاذبية الإعلانية ورضاك التام.',
    },
  ],
  sections: [
    {
      id: 'goals-platforms',
      step: '01',
      icon: '🎯',
      title: 'أهداف الفيديو والمنصات والمقاسات',
      desc: 'تحديد الغرض التسويقي من الفيديو والقنوات التي سيتم إطلاق الحملة عليها',
      fields: [
        {
          id: 'videoGoal',
          type: 'textarea' as const,
          label: 'الهدف الأساسي من الفيديو',
          outputKey: 'الهدف من الفيديو',
          icon: '🎯',
          required: true,
          rows: 2,
          placeholder:
            'مثال: إطلاق تطبيق جديد، شرح آلية عمل الخدمة، إعلان موسمي لزيادة المبيعات، فيديو توعوي...',
        },
        {
          id: 'videoProduct',
          type: 'textarea' as const,
          label: 'المنتج أو الخدمة المراد الإعلان عنها',
          outputKey: 'المنتج / الخدمة',
          icon: '🛍️',
          required: true,
          rows: 2,
          placeholder: 'اكتب اسم وتفاصيل ومميزات المنتج/الخدمة الرئيسية ونقاط البيع الفريدة...',
        },
        {
          id: 'platforms',
          type: 'multichip' as const,
          label: 'منصات النشر المستهدفة',
          outputKey: 'منصات النشر',
          icon: '📱',
          required: true,
          defaultValue: [
            'انستقرام (Instagram)',
            'سناب شات (Snapchat)',
            'تيك توك (TikTok)',
          ],
          options: [
            { value: 'انستقرام (Instagram)', label: 'انستقرام (Instagram)' },
            { value: 'سناب شات (Snapchat)', label: 'سناب شات (Snapchat)' },
            { value: 'تيك توك (TikTok)', label: 'تيك توك (TikTok)' },
            { value: 'يوتيوب (YouTube)', label: 'يوتيوب (YouTube)' },
            { value: 'إكس / تويتر (X)', label: 'إكس (Twitter / X)' },
            { value: 'شاشات عرض ومؤتمرات', label: 'شاشات عرض ومؤتمرات' },
            { value: 'تلفزيون (TV)', label: 'تلفزيون (TV)' },
          ],
        },
        {
          id: 'aspectRatio',
          type: 'select' as const,
          label: 'أبعاد ومقاس الفيديو المطلوب',
          outputKey: 'المقاس',
          icon: '📐',
          required: true,
          defaultValue: '9:16 (طولي - ستوريز وتيك توك وريلز)',
          options: [
            {
              value: '9:16 (طولي - ستوريز وتيك توك وريلز)',
              label: '9:16 (طولي - ستوريز وتيك توك وريلز وسناب شات)',
            },
            {
              value: '16:9 (أفقي - يوتيوب وشاشات عرض)',
              label: '16:9 (أفقي - يوتيوب ومواقع إلكترونية وشاشات)',
            },
            {
              value: '1:1 (مربع - انستقرام وبوستات)',
              label: '1:1 (مربع - انستقرام وتويتر وفيسبوك)',
            },
            {
              value: 'أكثر من مقاس (متعدد الأحجام)',
              label: 'أكثر من مقاس (تصدير بكافة الأبعاد المطلوبة)',
            },
          ],
        },
      ],
    },
    {
      id: 'script-message',
      step: '02',
      icon: '📝',
      title: 'السيناريو والرسالة الأساسية',
      desc: 'صياغة حبكة الفيديو والرسالة الجوهرية التي ستحرك المشاهد لاتخاذ الإجراء',
      fields: [
        {
          id: 'isScriptReady',
          type: 'yesno' as const,
          label: 'هل السيناريو الإعلاني (Script) جاهز لديك؟',
          outputKey: 'حالة السيناريو',
          icon: '📜',
          required: true,
          defaultValue: 'no' as const,
          yesLabel: 'نعم (السيناريو جاهز لدي)',
          noLabel: 'لا (نحتاج كتابة سيناريو احترافي)',
        },
        {
          id: 'scriptText',
          type: 'textarea' as const,
          label: 'نص أو ملف السيناريو الجاهز',
          icon: '✍️',
          required: true,
          rows: 3,
          placeholder: 'الصق نص السيناريو أو المشاهد هنا...',
          showIf: { field: 'isScriptReady', equals: 'yes' },
        },
        {
          id: 'scriptFiles',
          type: 'file' as const,
          label: 'ملف السيناريو',
          icon: '📄',
          accept: '.doc,.docx,.pdf,.txt',
          showIf: { field: 'isScriptReady', equals: 'yes' },
        },
        {
          id: 'keyMessage',
          type: 'textarea' as const,
          label: 'الرسالة الأساسية (Key Message)',
          outputKey: 'الرسالة الأساسية',
          icon: '💡',
          required: true,
          rows: 2,
          placeholder:
            'ما هي الفكرة والرسالة الأهم التي تريد أن تترسخ في ذهن المشاهد بعد الفيديو؟...',
        },
        {
          id: 'cta',
          type: 'text' as const,
          label: 'الدعوة لاتخاذ إجراء (Call To Action - CTA)',
          outputKey: 'الدعوة لإجراء CTA',
          icon: '📢',
          required: false,
          placeholder: 'مثال: اطلب الآن واستفد من الخصم، حمل التطبيق من الرابط، تواصل معنا...',
        },
      ],
    },
    {
      id: 'voiceover-assets',
      step: '03',
      icon: '🎙️',
      title: 'التعليق الصوتي (Voice Over) والملفات',
      desc: 'تحديد لهجة ونوع المعلق الصوتي وإرفاق الشعار وملفات الهوية',
      fields: [
        {
          id: 'hasVoiceOver',
          type: 'yesno' as const,
          label: 'هل تريد تعليق صوتي استوديو (Voice Over)؟',
          outputKey: 'التعليق الصوتي Voice Over',
          icon: '🎙️',
          required: true,
          defaultValue: 'yes' as const,
          yesLabel: 'نعم (تسجيل استوديو محترف)',
          noLabel: 'لا (مؤثرات موسيقية فقط)',
        },
        {
          id: 'voiceLang',
          type: 'select' as const,
          label: 'لغة ولهجة التعليق الصوتي',
          icon: '🗣️',
          required: true,
          defaultValue: 'لهجة سعودية خليجية',
          showIf: { field: 'hasVoiceOver', equals: 'yes' },
          options: [
            { value: 'عربية فصحى راقية', label: 'عربية فصحى راقية ورسمية (Standard Arabic)' },
            { value: 'لهجة سعودية خليجية', label: 'لهجة سعودية خليجية جذابة (Saudi / Gulf)' },
            { value: 'لهجة مصرية حيوية', label: 'لهجة مصرية حيوية وتفاعلية (Egyptian)' },
            { value: 'لهجة شامية', label: 'لهجة شامية (Levantine)' },
            { value: 'إنجليزية أمريكية (US English)', label: 'إنجليزية أمريكية (US English)' },
            { value: 'إنجليزية بريطانية (UK English)', label: 'إنجليزية بريطانية (UK English)' },
            { value: 'أخرى', label: 'أخرى' },
          ],
        },
        {
          id: 'voiceGender',
          type: 'select' as const,
          label: 'نبرة ونوع الصوت',
          icon: '👤',
          required: true,
          defaultValue: 'اترك الاختيار لفريق كوبالت',
          showIf: { field: 'hasVoiceOver', equals: 'yes' },
          options: [
            { value: 'صوت رجالي (Male Voice)', label: 'صوت رجالي فخم وإعلاني (Male Voice)' },
            { value: 'صوت نسائي (Female Voice)', label: 'صوت نسائي ناعم وواضح (Female Voice)' },
            {
              value: 'اترك الاختيار لفريق كوبالت',
              label: 'اترك الاختيار لفريق كوبالت للأفضلية',
            },
          ],
        },
        {
          id: 'logoFiles',
          type: 'file' as const,
          label: 'الشعار (Logo) بدقة فيكتور عالية',
          outputKey: 'الشعار المرفوع',
          icon: '🖼️',
          accept: 'image/*,.ai,.svg,.pdf',
          required: true,
        },
        {
          id: 'brandFiles',
          type: 'file' as const,
          label: 'ألوان وهوية العلامة التجارية',
          outputKey: 'الملفات المرفقة',
          icon: '🎨',
          accept: '.pdf,.ai,.zip,.png,.jpg',
        },
        {
          id: 'photoFiles',
          type: 'file' as const,
          label: 'صور المنتج أو لقطات الشاشة للتطبيق',
          outputKey: 'الملفات المرفقة',
          icon: '📸',
          accept: 'image/*,.zip',
          multiple: true,
        },
        {
          id: 'rawFiles',
          type: 'file' as const,
          label: 'مقاطع خام أو تسجيلات شاشة للتطبيق',
          outputKey: 'الملفات المرفقة',
          icon: '🎥',
          accept: 'video/*,.zip',
          multiple: true,
        },
        {
          id: 'refUrls',
          type: 'url_list' as const,
          label: 'فيديوهات مرجعية تفضل أسلوب تحريكها وإخراجها',
          outputKey: 'الفيديوهات المرجعية',
          placeholder: 'https://youtube.com/watch?v=... أو Vimeo',
          addButtonLabel: '➕ إضافة رابط فيديو مرجعي آخر',
        },
      ],
    },
  ],
};

const DIGITAL_MARKETING_FORM = {
  version: 2 as const,
  stepLabels: ['الأهداف والميزانية', 'الاستهداف والجمهور', 'المواد الإعلانية وسوابق الإعلانات'],
  guaranteesTitle: 'ضمانات كوبالت لخدمات إدارة الحملات الإعلانية',
  guarantees: [
    {
      icon: '📈',
      title: 'استهداف ذكي لتحقيق أعلى عائد ROAS',
      desc: 'نعتمد على بكسل التتبع وشرائح الجمهور المخصص لخفض تكلفة الاكتساب وزيادة المبيعات إلى أقصى حد.',
    },
    {
      icon: '📊',
      title: 'تقارير أداء ومتابعة تحليلية مستمرة',
      desc: 'تقارير يومية ولوحة بيانات توضح عدد النقرات، المبيعات، ومعدل التحويل بدقة وشفافية 100%.',
    },
    {
      icon: '⚙️',
      title: 'تحسين واختبار A/B Testing مستمر',
      desc: 'اختبار عناوين وفيديوهات وتصاميم متعددة للوصول لأفضل تركيبة إعلانية تحقق الربح بأقل تكلفة.',
    },
  ],
  sections: [
    {
      id: 'goals-budget',
      step: '01',
      icon: '🎯',
      title: 'أهداف الحملة، النشاط والميزانية',
      desc: 'تحديد مؤشرات الأداء المستهدفة (KPIs) والميزانية التشغيلية لمنصات الإعلانات',
      fields: [
        {
          id: 'campaignGoal',
          type: 'select' as const,
          label: 'الهدف الأساسي من الحملة الإعلانية',
          outputKey: 'هدف الحملة',
          icon: '🎯',
          required: true,
          defaultValue: 'مبيعات مباشرة (Purchases / E-commerce Sales)',
          options: [
            {
              value: 'مبيعات مباشرة (Purchases / E-commerce Sales)',
              label: 'مبيعات مباشرة للمتاجر (Sales / Purchases)',
            },
            {
              value: 'توليد عملاء محتملين (Leads Generation)',
              label: 'توليد واستقبال عملاء مهتمين (Leads Generation)',
            },
            {
              value: 'محادثات واتساب مباشرة (WhatsApp Messages)',
              label: 'محادثات واتساب ومراسلات فورية (WhatsApp Messages)',
            },
            {
              value: 'تحميل وتثبيت التطبيقات (App Installs)',
              label: 'تحميل وتثبيت التطبيقات (App Installs)',
            },
            {
              value: 'شهرة وانتشار العلامة (Brand Awareness)',
              label: 'شهرة وانتشار العلامة التجارية (Brand Awareness)',
            },
            {
              value: 'زيارات للموقع أو الفرع (Traffic / Store Visits)',
              label: 'زيارات للموقع أو الفروع (Traffic / Store Visits)',
            },
            { value: 'أخرى', label: 'هدف آخر مخصص' },
          ],
        },
        {
          id: 'productDesc',
          type: 'textarea' as const,
          label: 'المنتج أو الخدمة المراد الإعلان عنها',
          outputKey: 'المنتج / الخدمة',
          icon: '🛍️',
          required: true,
          rows: 2,
          placeholder: 'اكتب اسم المنتج/الخدمة، أبرز المميزات ونقاط القوة التنافسية...',
        },
        {
          id: 'budgetAmount',
          type: 'text' as const,
          label: 'الميزانية الإعلانية المقترحة للمنصات',
          outputKey: 'الميزانية الإعلانية',
          icon: '💵',
          required: true,
          placeholder: 'مثال: 3000',
          defaultValue: '2500',
        },
        {
          id: 'budgetCurrency',
          type: 'select' as const,
          label: 'عملة الميزانية',
          icon: '💱',
          required: true,
          defaultValue: 'SAR (ريال سعودي)',
          options: [
            { value: 'SAR (ريال سعودي)', label: 'SAR (ر.س)' },
            { value: 'AED (درهم إماراتي)', label: 'AED (د.إ)' },
            { value: 'USD (دولار)', label: 'USD ($)' },
            { value: 'KWD (دينار)', label: 'KWD (د.ك)' },
            { value: 'EGP (جنيه)', label: 'EGP (ج.م)' },
          ],
        },
        {
          id: 'durationDays',
          type: 'text' as const,
          label: 'مدة تشغيل الحملة الإعلانية المقترحة',
          outputKey: 'مدة الحملة',
          icon: '⏱️',
          required: true,
          placeholder: 'عدد الأيام',
          defaultValue: '14',
        },
        {
          id: 'landingUrl',
          type: 'text' as const,
          label: 'رابط صفحة الهبوط أو المتجر المستهدف للإعلانات',
          outputKey: 'رابط الهبوط',
          icon: '🌐',
          required: false,
          placeholder: 'https://yourstore.com/offer',
        },
        {
          id: 'socialUrls',
          type: 'url_list' as const,
          label: 'روابط حسابات السوشيال ميديا الحالية',
          outputKey: 'حسابات السوشيال',
          placeholder: 'https://instagram.com/yourbrand',
          addButtonLabel: '➕ إضافة رابط حساب آخر',
        },
      ],
    },
    {
      id: 'targeting',
      step: '02',
      icon: '🌍',
      title: 'الاستهداف الجغرافي والجمهور',
      desc: 'تحديد الشريحة المستهدفة والاهتمامات والدول والمدن لرفع معدل التحويل',
      fields: [
        {
          id: 'audienceDesc',
          type: 'textarea' as const,
          label: 'وصف واهتمامات الجمهور المستهدف',
          outputKey: 'وصف الجمهور المستهدف',
          icon: '👥',
          required: true,
          rows: 2,
          placeholder: 'الاهتمامات، السلوك الشرائي، المشاكل التي يحلها المنتج لجمهورك...',
        },
        {
          id: 'targetCountries',
          type: 'multichip' as const,
          label: 'الدول المستهدفة بالإعلانات',
          outputKey: 'الدول المستهدفة',
          icon: '🌍',
          required: true,
          defaultValue: ['المملكة العربية السعودية', 'الإمارات العربية المتحدة'],
          options: [
            { value: 'المملكة العربية السعودية', label: '🇸🇦 السعودية' },
            { value: 'الإمارات العربية المتحدة', label: '🇦🇪 الإمارات' },
            { value: 'الكويت', label: '🇰🇼 الكويت' },
            { value: 'قطر', label: '🇶🇦 قطر' },
            { value: 'البحرين', label: '🇧🇭 البحرين' },
            { value: 'سلطنة عمان', label: '🇴🇲 عمان' },
            { value: 'مصر', label: '🇪🇬 مصر' },
            { value: 'الأردن', label: '🇯🇴 الأردن' },
            { value: 'دول الخليج كافة', label: 'دول الخليج كافة' },
          ],
        },
        {
          id: 'cities',
          type: 'text' as const,
          label: 'مدن محددة للاستهداف',
          outputKey: 'المدن المستهدفة',
          icon: '🏙️',
          required: false,
          placeholder:
            'مثال: الرياض، جدة، الدمام، دبي، أبوظبي، الكويت... أو اتركها فارغة لكافة المدن',
        },
        {
          id: 'ageBrackets',
          type: 'multichip' as const,
          label: 'الفئات العمرية المستهدفة',
          outputKey: 'الفئات العمرية',
          icon: '🎂',
          required: false,
          defaultValue: ['25 - 34 سنة', '35 - 44 سنة'],
          options: [
            { value: '18 - 24 سنة', label: '18 - 24 سنة' },
            { value: '25 - 34 سنة', label: '25 - 34 سنة' },
            { value: '35 - 44 سنة', label: '35 - 44 سنة' },
            { value: '45 - 54 سنة', label: '45 - 54 سنة' },
            { value: '55+ سنة', label: '55+ سنة' },
          ],
        },
        {
          id: 'gender',
          type: 'select' as const,
          label: 'الجنس / النوع المستهدف',
          outputKey: 'الجنس',
          icon: '🚻',
          required: false,
          defaultValue: 'الجميع (رجال وسيدات)',
          options: [
            { value: 'الجميع (رجال وسيدات)', label: 'الجميع (رجال وسيدات)' },
            { value: 'رجال فقط', label: 'رجال فقط (Men Only)' },
            { value: 'سيدات فقط', label: 'سيدات فقط (Women Only)' },
          ],
        },
      ],
    },
    {
      id: 'creatives-history',
      step: '03',
      icon: '🎨',
      title: 'العروض، المواد الإعلانية وسجل الإعلانات',
      desc: 'تجهيز المواد الإعلانية، مراجعة الحملات السابقة، وتحليل المنافسين',
      fields: [
        {
          id: 'promoOffer',
          type: 'textarea' as const,
          label: 'تفاصيل العرض الترويجي والخصم',
          outputKey: 'العرض الترويجي',
          icon: '🎁',
          required: false,
          rows: 2,
          placeholder:
            'اكتب العرض الجذاب (مثال: خصم 30%، اشتري 1 واحصل على 1 مجاناً، كود خصم، شحن مجاني)...',
        },
        {
          id: 'priceNumber',
          type: 'text' as const,
          label: 'سعر المنتج في الإعلان (إن وجد)',
          outputKey: 'سعر المنتج المعلن',
          icon: '🏷️',
          required: false,
          placeholder: 'مثال: 199',
        },
        {
          id: 'needCreatives',
          type: 'yesno' as const,
          label: 'هل تحتاج تصاميم وفيديوهات إعلانية (Creatives) من فريقنا؟',
          outputKey: 'طلب تصميم Creatives',
          icon: '🎨',
          required: true,
          defaultValue: 'yes' as const,
          yesLabel: 'نعم (صمموا لي المواد الإعلانية)',
          noLabel: 'لا (المواد الإعلانية جاهزة لدي)',
        },
        {
          id: 'adImages',
          type: 'file' as const,
          label: 'رفع صور وتصاميم الإعلانات الجاهزة',
          outputKey: 'الملفات المرفقة',
          icon: '📸',
          accept: 'image/*,.zip',
          multiple: true,
        },
        {
          id: 'adVideos',
          type: 'file' as const,
          label: 'رفع فيديوهات وريلز الإعلانات',
          outputKey: 'الملفات المرفقة',
          icon: '🎥',
          accept: 'video/*,.zip',
          multiple: true,
        },
        {
          id: 'hasRunAdsBefore',
          type: 'yesno' as const,
          label: 'هل سبق لك تشغيل إعلانات ممولة من قبل؟',
          outputKey: 'إعلانات سابقة',
          icon: '📊',
          required: true,
          defaultValue: 'no' as const,
          yesLabel: 'نعم (لدي حملات سابقة)',
          noLabel: 'لا (أول تجربة إعلانية)',
        },
        {
          id: 'prevPlatforms',
          type: 'multichip' as const,
          label: 'المنصات السابقة التي أعلنت عليها',
          icon: '📱',
          required: true,
          defaultValue: ['سناب شات (Snapchat)', 'انستقرام (Instagram)'],
          showIf: { field: 'hasRunAdsBefore', equals: 'yes' },
          options: [
            { value: 'سناب شات (Snapchat)', label: 'Snapchat' },
            { value: 'انستقرام (Instagram)', label: 'Instagram' },
            { value: 'تيك توك (TikTok)', label: 'TikTok' },
            { value: 'إعلانات جوجل (Google Ads)', label: 'Google Ads' },
            { value: 'فيسبوك (Facebook Ads)', label: 'Facebook' },
            { value: 'إكس / تويتر (X Ads)', label: 'Twitter / X' },
            { value: 'لينكد إن (LinkedIn Ads)', label: 'LinkedIn' },
          ],
        },
        {
          id: 'prevResults',
          type: 'textarea' as const,
          label: 'نتائج وتحديات الحملات السابقة',
          icon: '📈',
          required: false,
          rows: 2,
          placeholder: 'اكتب تكلفة النقرة/التحويل التي حققتها، وما هي التحديات التي واجهتك...',
          showIf: { field: 'hasRunAdsBefore', equals: 'yes' },
        },
        {
          id: 'prevReports',
          type: 'file' as const,
          label: 'تقارير سابقة',
          icon: '📊',
          accept: '.pdf,.xlsx,.csv,image/*',
          multiple: true,
          showIf: { field: 'hasRunAdsBefore', equals: 'yes' },
        },
        {
          id: 'competitorUrls',
          type: 'url_list' as const,
          label: 'روابط المنافسين أو إعلانات تعجبك',
          outputKey: 'المنافسون',
          placeholder: 'https://competitor.com أو حساب منافس',
          addButtonLabel: '➕ إضافة رابط منافس آخر',
        },
      ],
    },
  ],
};

export const FORM_DEFINITIONS: Record<string, object> = {
  'social-media-posts': SOCIAL_MEDIA_POSTS_FORM,
  'website-design': WEBSITE_DESIGN_FORM,
  'ecommerce-store': ECOMMERCE_STORE_FORM,
  'motion-graphics': MOTION_GRAPHICS_FORM,
  'digital-marketing': DIGITAL_MARKETING_FORM,
};
